# Generated by Django 4.2.3 on 2023-08-02 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricetier',
            name='money_field',
        ),
        migrations.RemoveField(
            model_name='pricetier',
            name='money_field_currency',
        ),
    ]
