# Generated by Django 4.2.4 on 2023-08-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('колір', 'колір'), ('розмір', 'розмір')], max_length=100),
        ),
    ]
