# Generated by Django 4.2.4 on 2023-09-08 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_variation_variation_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='BicycleCharacteristics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wheel_diameter', models.CharField(blank=True, max_length=100, null=True)),
                ('brake_type', models.CharField(blank=True, max_length=100, null=True)),
                ('frame_material', models.CharField(blank=True, max_length=100, null=True)),
                ('frame_size', models.CharField(blank=True, max_length=100, null=True)),
                ('weight', models.CharField(blank=True, max_length=100, null=True)),
                ('rear_derailleur', models.CharField(blank=True, max_length=100, null=True)),
                ('gear_shifter', models.CharField(blank=True, max_length=100, null=True)),
                ('fork', models.CharField(blank=True, max_length=100, null=True)),
                ('cassete_ratchet', models.CharField(blank=True, max_length=100, null=True)),
                ('crank', models.CharField(blank=True, max_length=100, null=True)),
                ('speed_count', models.CharField(blank=True, max_length=100, null=True)),
                ('wheel_rear_hub', models.CharField(blank=True, max_length=100, null=True)),
                ('wheel_front_hub', models.CharField(blank=True, max_length=100, null=True)),
                ('bicycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
