# Generated by Django 4.2.3 on 2023-08-04 09:05

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_pricetier_money_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(currency_choices=[('USD', 'USD'), ('UAH', 'грн')], decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('USD', 'USD'), ('UAH', 'грн')], default='USD', editable=False, max_length=3),
        ),
    ]
