# Generated by Django 4.2.3 on 2023-07-28 11:41

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_discount_product_price_currency_alter_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('UAH', 'UAH'), ('USD', 'USD $')], default='USD', editable=False, max_length=3),
        ),
    ]
