# Generated by Django 4.2.3 on 2023-07-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_pricetier_delete_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetier',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
