# Generated by Django 4.2.3 on 2023-07-30 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_pricetier_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricetier',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier', to='store.product'),
        ),
    ]
