# Generated by Django 4.2.4 on 2023-08-11 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Оплата на карту', 'Оплата на карту'), ('Наложенний платіж', 'Наложенний платіж'), ('Готівкою при отриманні', 'Готівкою при отриманні')], default='Готівкою при отриманні', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, default=models.F('order_total'), editable=False, max_digits=14),
        ),
    ]
