# Generated by Django 4.2.4 on 2023-08-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_order_amount_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='remaining_balance',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Прийнято', 'Прийнято'), ('Комплектується', 'Комплектується'), ('Передано до служби доставки', 'Передано до служби доставки'), ('Відправлено', 'Відправлено'), ('Виконано', 'Виконано'), ('Скасовано', 'Скасовано')], default='New', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_status',
            field=models.CharField(choices=[('Оплата карткою', 'Оплата карткою'), ('Готівка', 'Готівка'), ('Наложенний платіж', 'Наложенний платіж')], default='Оплата карткою', max_length=50),
        ),
    ]
